### ISSUE TITLE
How to use "md5" and "sqrt"?

### ISSUE THREAD

**Issue by anta40** [MaoKo/Unix-Like#3]
After booting and type `help`, Unix-Like will show you all available commands.
How to use "sqrt", for example?

I type:
`sqrt 16`

And the result is:
`#`

Hmm... nothing?

And how to use "md5"?

I type
`md5 "Hello"`

The output is:
`Invalid command`

**Comment by MaoKo** [comment]
Hi. I will git push soon. For sqrt it's just to see if SSE is on the machine. I rename the command. And md5 I just comment the ebx before the int 030H.
